<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s role="alert">'
        . '<button type="button" class="close" data-dismiss="alert" '
        . 'aria-label="Close"><span aria-hidden="true">&times;</span></button>'
        . '<div>')
        ->setMessageSeparatorString('</div><div>')
        ->setMessageCloseString('</div></div>');
?>
<?= $this->flashMessenger()->render(
        'success',
        ['alert', 'alert-dismissible', 'alert-success']
        )
?>